### ISSUE TITLE
Летающие шарики

### ISSUE THREAD

**Issue by lizagrishkova** [lizagrishkova/prog_grishkova#10]
590f551dfa74e5fe4bca53af0450aa3e0e1c5976 @antosha417

**Comment by antosha417** [comment]
Перейди по ссылке в своём коментарии и убедись, что там то, что ты хотела. Я не нашёл там шариков летающих.

**Comment by lizagrishkova** [comment]
Да, их действительно там нет, извиняюсь. Тут есть b511bdd. @antosha417

**Comment by antosha417** [comment]
Сделай линейную шкалу скорости

**Comment by antosha417** [comment]
Однобуквенные переменные - плохо. Если используешь глобальные переменные, то по pep8 их большими буквами нужно называть.
Перепиши функцию `tick_handler` хорошо, подумай как это сделать.

**Comment by antosha417** [comment]
Объясни зачем ты что-то в консоль выводишь?

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by lizagrishkova** [comment]
6d13b0ed01ddceaa2232deadd64a760f9f1294ba @antosha417 
Что значит: линейная шкала скорости?

**Comment by antosha417** [comment]
Ругается ошибками, забыла event принять у анфризера ![latest-screenshot](https://user-images.githubusercontent.com/14187674/48550676-82d53b00-e8e4-11e8-877f-3bdd6e96ea39.png)

`cnt` - не хорошее название для глобальной переменной, давай что-то вроде `AMOUNT_OF_BALLS`

**Comment by antosha417** [comment]
Поправь и закрывай issue

**Comment by lizagrishkova** [comment]
ea631bc6c3a8cc9c5aae40574e48d45c0cb3ebe7 @antosha417
