### ISSUE TITLE
Анимация

### ISSUE THREAD

**Issue by lizagrishkova** [lizagrishkova/prog_grishkova#11]
590f551  @antosha417

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by lizagrishkova** [comment]
5571a1fb818fe5baf5e97c375c91c4ac7f94db86 @antosha417 Поправлено

**Comment by antosha417** [comment]
Везде где у тебя к названиям переменных прилеплены цифры нужно переписать через циклы.
```python
for line_coords in ((0, 0), (1, 1)), \
                   ((2, 3), (5, 10)), \
                   ((100500, 3), (5, 10)):
    do_something(line_coords)
```

**Comment by antosha417** [comment]
Пока ставлю тебе  06 за задачу, чтобы поднять поправь код.

**Comment by antosha417** [comment]
У тебя стояла единичка за графику, не нашёл issue где ты её сдала, поставил 0 пока.

**Comment by antosha417** [comment]
Мне кажется ты не сдала ещё графику, а я промахнулся и не туда поставил.

**Comment by lizagrishkova** [comment]
928cc92d8d3fd7929749c6cb29b4709b73e7608e @antosha417 
Переписала на основе графики

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

Пока ставлю тебе 0,8  за задачу, чтобы поднять поправь код.

**Comment by lizagrishkova** [comment]
656f78a7ce15c61852d3b821b9c3f8def24379a6 @antosha417 Поправила

**Comment by antosha417** [comment]
Закрывай
