### ISSUE TITLE
Черепашка

### ISSUE THREAD

**Issue by lizagrishkova** [lizagrishkova/prog_grishkova#15]
bbd8fa6ff0ace8cf399e4aaed5d2f66d8f389043
308d5031d561bff67e82961448c0b59aa69bf05c
@antosha417

**Comment by lizagrishkova** [comment]
79d52ca381c6da8032cc594f22126af4920a10b5 @antosha417 Фракталы

**Comment by antosha417** [comment]
Хорошо, закрывай
