### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by antosha417** [lizagrishkova/prog_grishkova#2]
https://github.com/lizagrishkova/prog_grishkova/blob/0f83e9085c4844624902e5716a97765faa89111d/lab4%20%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D1%83/task3.py#L4-L21
До и после объявления функции должно быть 2 пустые строки

**Comment by lizagrishkova** [comment]
Поправила

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by lizagrishkova** [comment]
b988c3396d1a77d1e50afa8a89bc68a892612fbb

**Comment by antosha417** [comment]
Не обязательно после  `def some_function_name:` оставлять пустую строчку.
