### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by antosha417** [lizagrishkova/prog_grishkova#3]
https://github.com/lizagrishkova/prog_grishkova/blob/0f83e9085c4844624902e5716a97765faa89111d/lab4%20%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D1%83/task3.py#L36-L71
у тебя постоянно повторяются 3 строчки, ты создаёшь объект рисуешь его в окне и заполняешь цветом, давай функцию, а?

**Comment by lizagrishkova** [comment]
Как передавать то, что мы хотим нарисовать? Это же в каждом случае разный объект(oval, polygon, circle)

**Comment by antosha417** [comment]
Попробуй сделать функцию и передавать ей параметры

**Comment by lizagrishkova** [comment]
Я не понимаю как передавать форму того, что хотим нарисовать. А еще от формы зависит количество координат, которые надо передать.

**Comment by antosha417** [comment]
Мы же уже передавали функции внутрь других функций. Функции такие же объекты. 

> от формы зависит

Давай теперь вспомним структуру данных в которой мы можем положить несколько координат, неважно сколько

**Comment by lizagrishkova** [comment]
Написала функцию для отрисовки и заполнения объекта

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by lizagrishkova** [comment]
b988c3396d1a77d1e50afa8a89bc68a892612fbb
47f682250aeb9b81baf4ea5f4158dc5171775ff4

**Comment by antosha417** [comment]
Давай сделаем ещё одну функцию похожую на `draw`, она будет принимать массив координат и рисовать многоугольник.

**Comment by lizagrishkova** [comment]
18f53007b5171295c7ab56c7fd6eeee14f8d4248 @antosha417

**Comment by antosha417** [comment]
Супер! можно ещё переименовать `f` )
