### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by antosha417** [lizagrishkova/prog_grishkova#4]
https://github.com/lizagrishkova/prog_grishkova/blob/0f83e9085c4844624902e5716a97765faa89111d/lab4%20%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D1%83/task3.py#L22

https://github.com/lizagrishkova/prog_grishkova/blob/0f83e9085c4844624902e5716a97765faa89111d/lab4%20%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D1%83/task3.py#L83

пробелы после запятых

**Comment by lizagrishkova** [comment]
поправила

**Comment by lizagrishkova** [comment]
47f682250aeb9b81baf4ea5f4158dc5171775ff4

**Comment by lizagrishkova** [comment]
b988c3396d1a77d1e50afa8a89bc68a892612fbb

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста во всех файлах твоего проекта

**Comment by lizagrishkova** [comment]
@antosha417 b511bdd92e22f879f35b5e5aeef2a3e13363086c поправила

**Comment by antosha417** [comment]
Что за файл`.idea/vcs.xml`? Нужно смотреть какие файлы включаешь в коммит, читать их и задавать себе вопрос хочешь ли ты это сдавать. Это системный файл пайчарма, его в проекте быть не должно, у моего пайчарма другие системные файлы, например. Удали этот файл. Здорово еще будет погуглить по словам `gitignore`.

Прочитай правила игры и создай issue на задачи, хорошо?

**Comment by lizagrishkova** [comment]
e27ee2f1479483d1d2fcf905280186dbfab5363d удалила
@antosha417

**Comment by lizagrishkova** [comment]
на каждое задание надо новый issue?

**Comment by antosha417** [comment]
Да
