### ISSUE TITLE
Это место для докстринг ты оставила?

### ISSUE THREAD

**Issue by antosha417** [lizagrishkova/prog_grishkova#5]
https://github.com/lizagrishkova/prog_grishkova/blob/6bd7b20b7fa5b57a063acb81e07ab58403c4de43/lab4%20%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D1%83/animation.py#L8-L9

**Comment by lizagrishkova** [comment]
Не должно быть 2 строки до и после объявления функции? Или одна до и одна после?

**Comment by antosha417** [comment]
Прогони pylint или что угодно ещё что поддерживает твоя среда или просто почитай pep и всё узнаешь.

**Comment by lizagrishkova** [comment]
Убрала

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by lizagrishkova** [comment]
590f551dfa74e5fe4bca53af0450aa3e0e1c5976

**Comment by antosha417** [comment]
Молодец, как проверяла, что код написал по пеп8?

**Comment by lizagrishkova** [comment]
Поставила pycharm

**Comment by antosha417** [comment]
замечательно
