### ISSUE TITLE
Второе задание лабораторной работы по графике

### ISSUE THREAD

**Issue by lizagrishkova** [lizagrishkova/prog_grishkova#7]
590f551dfa74e5fe4bca53af0450aa3e0e1c5976 @antosha417

**Comment by antosha417** [comment]
Назови хорошо

**Comment by lizagrishkova** [comment]
Сделано

**Comment by antosha417** [comment]
По ссылке выше анимация, а не лаба по графике

**Comment by lizagrishkova** [comment]
b511bdd92e22f879f35b5e5aeef2a3e13363086c
@antosha417

**Comment by antosha417** [comment]
Там опять куча файлов по ссылке, как мне найти там лабу по графике?
