### ISSUE TITLE
Третье задание лабораторной работы по графике

### ISSUE THREAD

**Issue by lizagrishkova** [lizagrishkova/prog_grishkova#8]
590f551dfa74e5fe4bca53af0450aa3e0e1c5976 @antosha417

**Comment by antosha417** [comment]
По ссылке выше анимация, это не лаба по графике

**Comment by antosha417** [comment]
И вообще зачем создавать 4 файла с одной и той же программой? Гит - система контроля версий, почему не сделать наивную версию программы, а потом не улучшать её, создавая новые версии(коммиты)

**Comment by lizagrishkova** [comment]
ad73a6f3380bd31cee17988591f12eb80d54d5cc @antosha417 
Добилась работоспособности с map

**Comment by antosha417** [comment]
Замечательно, закрывай

**Comment by antosha417** [comment]
Анимацию лучше в этот код засунуть
