### ISSUE TITLE
Игра "Поймай шарик"

### ISSUE THREAD

**Issue by lizagrishkova** [lizagrishkova/prog_grishkova#9]
590f551dfa74e5fe4bca53af0450aa3e0e1c5976 @antosha417

**Comment by antosha417** [comment]
По ссылке выше нет игры поймай шарик

**Comment by lizagrishkova** [comment]
e27ee2f1479483d1d2fcf905280186dbfab5363d

**Comment by lizagrishkova** [comment]
03b37c9ca534bd44fab8d4be0caa9e09587f5ffb

**Comment by lizagrishkova** [comment]
b511bdd92e22f879f35b5e5aeef2a3e13363086c
@antosha417

**Comment by antosha417** [comment]
По ссылке выше есть файл `.idea/vcs.xml` что это такое? Как мне его оценивать?

**Comment by antosha417** [comment]
Коммит про пеп8, а не про задачу поймай шарик. Сложно разобраться

**Comment by antosha417** [comment]
когда кликаю много раз на один шарик мне даёт много очков, хочу только 1 на 1 шарик

**Comment by lizagrishkova** [comment]
cd2c8da9a3e6ce953a1241e464190be9cb97b570 @antosha417 Исправила

**Comment by antosha417** [comment]
Закрывай
